os: linux
dist: trusty
sudo: required
language: java

addons:
  firefox: "59.0"
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "chmod a+x drivers/*" # Make drivers executable

script:
  - mvn clean test -Pdev -e