name: Java CI with Maven
run-name: ${{ github.event.inputs.env || 'dev' }} Test using ${{ github.event.inputs.browser || 'edge' }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Trigger the workflow manually
    inputs:
      tags: # Input parameter for test scenario tags
        description: "Test scenario tags"
        required: true
        default: "smoke"
      env:
        type: choice
        required: true
        description: Select environment
        options:
          - local
          - dev
          - qa
          - stage
          - prod
        default: dev
      browser:
        description: Browser
        required: true
        default: "edge"
        type: choice
        options:
          - chrome
          - edge
env:
  PROFILE: ${{ github.event.inputs.env || 'dev' }}
  BROWSER: ${{ github.event.inputs.browser || 'edge' }}


jobs:
  build-maven:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo # Step to check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '17'

      # Cache save and restore
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Prepare Allure history
      run: |
        mkdir -p allure-results

    - name: Run tests with Maven
      run: mvn -B clean test -P$PROFILE -DBrowser=$BROWSER -Dallure.results_pattern=allure-results

    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure report action
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 5

    - name: Deploy Allure report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages # Specify the branch to publish the report to
        publish_dir: allure-history

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
