name: Java CI with Maven
run-name: ${{ github.event.inputs.env || 'dev' }} Test using ${{ github.event.inputs.browser || 'edge' }}

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Trigger the workflow manually
    inputs:
      tags: # Input parameter for test scenario tags
        description: "Test scenario tags"
        required: true
        default: "smoke"
      env:
        type: choice
        required: true
        description: Select environment
        options:
          - local
          - dev
          - qa
          - stage
          - prod
        default: dev
      browser:
        description: Browser
        required: true
        default: "edge"
        type: choice
        options:
          - chrome
          - edge
env:
  PROFILE: ${{ github.event.inputs.env || 'dev' }}
  BROWSER: ${{ github.event.inputs.browser || 'edge' }}
  MAVEN_TESTS_RUN: false # a flag to see if the test triggered or not

jobs:
  build-maven:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo # Step to check out the repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: '17'

#    - uses: browser-actions/setup-chrome@v1
#    - run: chrome --version

    - uses: browser-actions/setup-edge@v1
    - name: Run PowerShell commands
      shell: pwsh
      run: |
        $version = (Get-Item (Get-Command msedge).Source).VersionInfo.ProductVersion
        Write-Output "Microsoft Edge version: $version"

      # Cache save and restore
    - uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Prepare Allure history
      run: |
        mkdir -p allure-results

    - name: Run tests with Maven
      run: mvn -B clean test -P${{ env.PROFILE }} -DBrowser=${{ env.BROWSER }} -Dallure.results_pattern=allure-results

    - name: Set MAVEN_TESTS_RUN to true
      if: always() # Ensure this step runs even if previous steps fail
      run: echo "MAVEN_TESTS_RUN=true" >> $GITHUB_ENV

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

  generate-allure-report:
    runs-on: ubuntu-latest
    needs: build-maven # This ensures that the generate-allure-report job runs after build-maven
    steps:
    - name: Get Allure history
      uses: actions/checkout@v3
      continue-on-error: true
      with:
        ref: allure-report
        path: allure-report

    - name: Allure report action
      uses: simple-elf/allure-report-action@master
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 5

    - name: Deploy Allure report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: allure-report # Specify the branch to publish the report to
        publish_dir: allure-history
